// Info: Render-hint props for every component. Used by the test harness
// render matrix and by the demo showcase's SampleCard.js. One source,
// two consumers. Each entry provides the minimal prop set that lets a
// component render a non-empty output without throwing.
//
// Callbacks are no-ops; the harness does not assert behavior, only render.

const noop = function () {};

export default {
  Button: { children: 'Button', onPress: noop },
  IconButton: { name: 'add', onPress: noop },
  Tag: { label: 'Tag' },
  Heading: { children: 'Heading' },
  Text: { children: 'Text' },
  Link: { children: 'Link', onPress: noop },
  InlineLink: { title: 'Inline link', onPress: noop },
  ProgressBar: { value: 0.6 },
  Slider: { value: 50, onChange: noop },
  Toggle: { value: true, onValueChange: noop },
  Checkbox: { checked: true, onChange: noop },
  RadioButton: { checked: true, onChange: noop },
  Loading: { label: 'Loading' },
  InlineLoading: { status: 'active', label: 'Loading' },
  Skeleton: { width: 120, height: 16 },
  SkeletonText: { width: 160 },
  SkeletonPlaceholder: { width: 120, height: 40 },
  BadgeIndicator: { count: 5 },
  ShapeIndicator: { shape: 'circle', size: 16 },
  IconIndicator: { iconName: 'information-circle', size: 24 },
  UserAvatar: { initials: 'AB' },
  TruncatedText: { children: 'A long piece of text that should truncate', maxLines: 1 },
  CodeSnippet: { code: 'npm install' },
  CopyButton: { text: 'copied text', onCopy: noop },
  FormLabel: { children: 'Label' },
  Notification: { title: 'Title', subtitle: 'Subtitle' },
  ToastNotification: { title: 'Title', subtitle: 'Subtitle' },
  StaticNotification: { title: 'Title', subtitle: 'Subtitle' },
  Callout: { title: 'Title', children: 'Body' },
  Tile: { title: 'Tile' },
  ClickableTile: { title: 'Clickable tile', onPress: noop },
  SelectableTile: { title: 'Selectable tile' },
  BreadcrumbItem: { children: 'Item', href: '#' },
  Tab: { label: 'Tab', onPress: noop },
  TabPanel: { children: 'Panel' },
  AccordionItem: { title: 'Item', children: 'Body' },
  ProgressStep: { label: 'Step' },
  Switch: { label: 'Switch', selected: true, onPress: noop },
  TreeNode: { label: 'Node' },
  PaginationNav: { totalPages: 5, currentPage: 1, onChange: noop },
  MenuItem: { label: 'Menu item', onPress: noop },
  MenuItemSelectable: { label: 'Selectable', checked: false, onChange: noop },
  ModalHeader: { title: 'Header' },
  ModalBody: { children: 'Body' },
  ModalFooter: { children: 'Footer' },
  Tooltip: { label: 'Tooltip info' },
  DefinitionTooltip: { term: 'Term', definition: 'Definition' },
  Toggletip: { content: 'Tip info' },
  ErrorState: { title: 'Error', subtitle: 'Something went wrong' },
  LandingView: { children: 'Landing' },
  ListItem: { title: 'List item' },
  ContainedListItem: { children: 'List item' },
  NavigationListItem: { title: 'Nav item' },
  OrderedList: { children: 'List' },
  UnorderedList: { children: 'List' },
  StructuredListCell: { children: 'Cell' },
  StructuredListRow: { children: 'Row' },
  Column: { children: 'Column' },
  Row: { children: 'Row' },
  Grid: { children: 'Grid' },
  FlexGrid: { children: 'FlexGrid' },
  Stack: { children: 'Stack' },
  ButtonSet: { children: 'ButtonSet' },
  Section: { children: 'Section' },
  Content: { children: 'Content' },
  Copy: { children: 'Copy' },
  Filename: { name: 'file.txt' },
  HeaderName: { text: 'Nimbus' },
  HeaderMenuItem: { text: 'Item', onPress: noop },
  HeaderGlobalAction: { icon: 'add', onPress: noop },
  SideNavLink: { text: 'Link', onPress: noop },
  SideNavItem: { text: 'Item', onPress: noop },
  SideNavMenu: { label: 'Menu' },
  SideNavSwitcher: { label: 'Switcher', options: [] },
  SwitcherItem: { text: 'Item', onPress: noop },
  SelectItem: { text: 'Option', value: 'opt1' },
  SelectableTag: { text: 'Tag' },
  DismissibleTag: { text: 'Tag', onDismiss: noop },
  OperationalTag: { text: 'Tag' },
  RadioTile: { name: 'group', value: 'a', checked: true },
  FileUploaderButton: { label: 'Upload', onPress: noop },
  TableToolbar: { children: 'Toolbar' },
  TableBatchAction: { children: 'Action' },
  TableBatchActions: { children: 'Actions' },
  TableActionList: { children: 'List' },
  OverflowMenuItem: { text: 'Item', onPress: noop },
  NotificationButton: { children: 'Button' },
  NotificationActionButton: { children: 'Action' },
  DatePickerInput: { placeholder: 'mm/dd/yyyy' },
  PasswordInput: { placeholder: 'Password' },
  NumberInput: { value: 5, onChange: noop },
  Search: { placeholder: 'Search...', onChange: noop },
  ExpandableSearch: { placeholder: 'Search...', onChange: noop },
  Dropdown: { triggerLabel: 'Dropdown', items: [], onSelect: noop },
  FormItem: { children: 'Item' },
  Form: { children: 'Form' },
  FormContext: { children: 'Form' },
  FormGroup: { children: 'Group' },
  PrefixContext: { children: 'Prefix' },
  ErrorBoundaryContext: { children: 'Boundary' },
  GlobalTheme: { children: 'Theme' },
  HeaderContainer: { children: 'Container' },
  HeaderMenu: { children: 'Menu' },
  HeaderPanel: { children: 'Panel' },
  HeaderSideNavItems: { children: 'Items' },
  SideNav: { children: 'Nav' },
  SideNavItems: { children: 'Items' },
  SideNavDivider: { children: 'Divider' },
  SideNavFooter: { children: 'Footer' },
  SideNavHeader: { children: 'Header' },
  SideNavIcon: { name: 'menu' },
  SideNavDetails: { children: 'Details' },
  SideNavLinkText: { children: 'Link' },
  SideNavMenuItem: { children: 'Item' },
  SwitcherDivider: { children: 'Divider' },
  SkipToContent: { targetId: 'main-content' },
  HeaderNavigation: { children: 'Nav' },
  HeaderMenuButton: { onPress: noop },
  IconSwitch: { icon: 'add', checked: true, onToggle: noop },
  IconTab: { icon: 'add', active: true, onPress: noop },
  TabContent: { children: 'Content' },
  TableHeader: { children: 'Header' },
  TableBody: { children: 'Body' },
  TableHead: { children: 'Head' },
  TableRow: { children: 'Row' },
  TableCell: { children: 'Cell' },
  TableContainer: { children: 'Table' },
  StructuredListHead: { children: 'Head' },
  StructuredListBody: { children: 'Body' },
  StructuredListWrapper: { children: 'Wrapper' },
  StructuredListInput: { children: 'Input' },
  Table: { children: 'Table' },
  TableHeaderSelected: { count: 2 },
  UiPanelItem: { text: 'Item', onPress: noop },
  BottomToolbarPrimaryAction: { primaryAction: { label: 'Action', onPress: noop } },
  AcceptTerms: { children: 'Terms' },
  ActionableNotification: { title: 'Title', subtitle: 'Subtitle' }
};
